language: r
    
cache: packages

branches:
    only:
        - website-source
        
r_github_packages:
    - rstudio/blogdown

before_script:
    - Rscript -e 'blogdown::install_hugo()'

script:
    - Rscript -e 'blogdown::build_site()'
    
before_deploy:
    - cd $TRAVIS_BUILD_DIR

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: website-source
    local_dir: docs
    repo: chircollab/chircollab.github.io
    target_branch: master
