language: r
dist: xenial
latex: false

branches:
  only:
    - website-source

cache:
  packages: yes
  directories:
    - $HOME/bin

before_script:
  - Rscript -e 'blogdown::install_hugo()'

script:
  - Rscript -e 'blogdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: website-source
  local_dir: public
  target_branch: master