# Site settings
baseurl = "https://chirunconf.github.io"
canonifyurls = true
relativeurls = false
languageCode = "en-us"
title = "Chicago R Unconference"
location = "Chicago 2018"
theme = "hugo-ropensci-theme"
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Chicago R Unconference"
  description = "Chicago, Illinois. March 9-10 2018"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Sorry, but you seem to have become lost."
    text = "Please visit [the front page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Chicago R Unconference"
    # Optional logo as brand stored in img/
    logo = "logo.png"
    about = "What"
    team = "Who"
    joinus="Join Us"
    venue = "Venue"
    sponsors = "Sponsors"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Chicago R Unconference"
    subtitle = "March 9-10, 2019 • Chicago, Illinois"
    buttonText = "Tell me more"


   # About section
   [params.about]
    enable = true
    title = "Launching the Chicago R Unconference"
    text = "Inspired by the [rOpenSci](https://ropensci.org/) [unconference series](http://unconf18.ropensci.org/), we're putting together a Chicago-based unconference to encourage open source contribution and development in the Chicago R community. Our goal is to encourage diverse groups to develop open source packages and to contribute to the larger R community. We plan to bring together attendees from industry, academia, government, nonprofits, and more. We'll spend two days collaborating with each other, building R packages and learning from each other.\n\n Not sure how this works? No worries, that probably means you should attend this event! Check out [writeups](https://ropensci.org/blog/2017/10/31/ozunconf2017/) [of](https://ropensci.org/blog/2017/11/17/unconf-sixtips/) [previous](https://ropensci.org/blog/2018/06/05/unconf18/) [unconferences](https://blog.revolutionanalytics.com/2018/05/reflections-on-the-ropensci-unconference.html) for details on how this generally works, and take a look at [past](https://github.com/ropensci/unconf18/issues) [Github](https://github.com/ropensci/ozunconf18/issues/) [issues](https://github.com/ropensci/unconf17) to get a sense of the projects people work on. Projects might include creating new packages from scratch, writing new vignettes, or closing issues on existing packages. We plan to have something for everyone to contribute, even if you consider yourself a beginner! \n\n Because we want our attendees to have a safe, enjoyable, and friendly experience at the unconf, we have a [code of conduct](/coc) that we encourage you to read.  \n\n Additionally, you can find the Github repo for this year's #chirunconf [here](https://github.com/chirunconf/chirunconf19)."

  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Participants"
    text = "Our team is dedicated to inspiring beginners and those new to open source to contribute to the R community. We've worked in industry and academia alike, and we believe that open source is at its best when it draws from diverse contributors. \n \n Note: Mentors for this event are denoted with an asterisk."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    
    [[params.team.members]]
      name = "Angela Li*"
      position = "Center for Spatial Data Science, UChicago"
      img = "angela-li.jpg"
      twitter = "CivicAngela"
      github = "angela-li"
      url = "https://www.angela-li.github.io"

    [[params.team.members]]
      name = "Emily Riederer*"
      position = "Capital One"
      img = "emily-riederer.jpg"
      twitter = "EmilyRiederer"
      github = "EmilyRiederer"
      url = "https://www.emilyriederer.netlify.com"
      
    [[params.team.members]]
      name = "Alex Hayes*"
      position = "UW-Madison"
      img = "alex-hayes.jpeg"
      twitter = "alexpghayes"
      github = "alexpghayes"
      url = "https://www.alexpghayes.com"
      
    [[params.team.members]]
      name = "Amanda Dobbyn*"
      position = "Earlybird Software"
      img = "amanda-dobbyn.jpeg"
      twitter = "dobbleobble"
      github = "aedobbyn"
      url = "https://dobb.ae"
      
    [[params.team.members]]
      name = "David Smith*"
      position = "Microsoft"
      img = "david-smith.jpg"
      twitter = "revodavid"
      github = "revodavid"
      url = "http://blog.revolutionanalytics.com"

    [[params.team.members]]
      name = "Jim Hester*"
      position = "RStudio"
      img = "jim-hester.jpg"
      twitter = "jimhester_"
      github = "jimhester"
      url = "https://www.jimhester.com"

    [[params.team.members]]
      name = "Will Landau*"
      position = "Eli Lilly and Company"
      img = "will-landau.jpg"
      twitter = "wmlandau"
      github = "wlandau"
      url = "https://wlandau.github.io"
      
    [[params.team.members]]
      name = "Sam Tyner*"
      position = "Iowa State University"
      img = "sam-tyner.png"
      twitter = "sctyner"
      github = "sctyner"
      url = "https://sctyner.github.io"

    [[params.team.members]]
      name = "Karl Broman*"
      position = "Biostatistics & Medical Informatics, UW-Madison"
      img = "karl-broman.jpg"
      twitter = "kwbroman"
      github = "kwbroman"
      url = "https://kbroman.org"

    [[params.team.members]]
      name = "John Blischak*"
      position = "Department of Human Genetics, UChicago"
      img = "john-blischak.jpg"
      twitter = "jdblischak"
      github = "jdblischak"
      url = "https://jdblischak.com/"
    
    [[params.team.members]]
      name = "Deblina Mukherjee"
      position = "UChicago"
      img = "deblina-mukherjee.jpeg"
      twitter = "deblnia"
      github = "deblnia"

    [[params.team.members]]
      name = "Mauro Lepore"
      position = "Smithsonian"
      img = "mauro-lepore.jpg"
      twitter = "mauro_lepore"
      github = "maurolepore"
      url = "https://maurolepore.github.io/" 
      
    [[params.team.members]]
      name = "Katherine Simeon"
      position = "Northwestern University, R-Ladies Chicago"
      img = "katherine-simeon.jpg"
      twitter = "kitkatbar429"
      github = "katherinesimeon"

    [[params.team.members]]
      name = "Natalie Jorion"
      position = "Pearson VUE"
      img = "natalie-jorion.jpg"
      url = "https://nataliejorion.com"

    [[params.team.members]]
      name = "Wei Yang Tham"
      position = "Ohio State"
      img = "wei-yang-tham.jpeg"
      twitter = "wytham88"
      github = "weiyangtham"
      url = "https://wytham.rbind.io/"

    [[params.team.members]]
      name = "Florencia Mangini"
      position = "R-Ladies Chicago"
      img = "florencia-mangini.jpeg"
      twitter = "manginiflor"
      github = "frm1789"
      url = "https://thinkingondata.com"

    [[params.team.members]]
      name = "Joshua Goldberg"
      position = "Nuveen"
      img = "josh-goldberg.jpeg"
      twitter = "goldbergdata"
      github = "goldbergdata"

    [[params.team.members]]
      name = "William Bonnell"
      position = "NORC, UChicago"
      img = "william-bonnell.jpeg"
      twitter = "_willdebras"

    [[params.team.members]]
      name = "Sharla Gelfand"
      position = "College of Nurses of Ontario"
      img = "sharla-gelfand.jpeg"
      twitter = "sharlagelfand"
      github = "sharlagelfand"
      url = "https://sharla.party/" 
      
    [[params.team.members]]
      name = "Caroline Kinnen"
      position = "KIPP Chicago"
      img = "caroline-kinnen.jpeg"

    [[params.team.members]]
      name = "Smitha Shivakumar"
      position = "PPM America, Inc."
      img = "smitha-shivakumar.jpeg"
      twitter = "SmithaShivakuma"
      github = "SmithaShivakumar"

    [[params.team.members]]
      name = "Pierre DeBois"
      position = "Zimana"
      img = "pierre-debois.jpg"
      twitter = "zimanaanalytics"
      github = "zimana"      

    [[params.team.members]]
      name = "Chase Clark"
      position = "UIC"
      img = "chase-clark.jpg"
      twitter = "ChasingMicrobes"
      github = "chasemc"
      url = "chasemc.github.io"

    [[params.team.members]]
      name = "Zaynaib Giwa"
      position = "R-Ladies Chicago"
      img = "zaynaib-giwa.png"
      twitter = "AmazingSpeciali"
      github = "Zaynaib"
      url = "https://medium.com/@zaynaibg"

    [[params.team.members]]
      name = "Eric Nantz"
      position = "The R Podcast"
      img = "eric-nantz.jpg"
      twitter = "theRcast"
      github = "rpodcast"
      url = "https://r-podcast.org"
      
    [[params.team.members]]
      name = "Shengying Chen"
      position = "World Financial Group"
      img = "shengying-chen.jpeg"

    [[params.team.members]]
      name = "Kanishka Misra"
      position = "Purdue"
      img = "kanishka-misra.jpg"
      twitter = "iamasharkskin"
      github = "kanishkamisra"
      url = "https://kanishka.xyz"

    [[params.team.members]]
      name = "Kristi Angel"
      position = "Groupon"
      img = "kristi-angel.jpg"
      github = "kangel09"

    [[params.team.members]]
      name = "Indrajeet Patil"
      position = "Harvard"
      img = "indrajeet-patil.jpg"
      twitter = "patilindrajeets"
      github = "IndrajeetPatil"
      url = "https://sites.google.com/site/indrajeetspatilmorality/"

    [[params.team.members]]
      name = "Caroline Williams"
      position = "R-Ladies Chicago"
      img = "caroline-williams.jpg"
      twitter = "ckwill36"
      github = "ckwms63"
      url = "https://ASGchicago.github.io"

    [[params.team.members]]
      name = "Ben Listyg"
      position = "Wyzant"
      img = "ben-listyg.jpg"
      twitter = "benlistyg"
      github = "blistyg"
      url = "https://blistyg.github.io/"

    [[params.team.members]]
      name = "Tristan Mahr"
      position = "Wisconsin Intelligibility"
      img = "tristan-mahr.jpg"
      twitter = "tjmahr"
      github = "tjmahr"
      url = "https://www.tjmahr.com/"

    [[params.team.members]]
      name = "Abigail Smith"
      position = "Northwestern University"
      img = "abigail-smith.jpg"
      twitter = "flabbysmith"
      github = "abbylsmith"
      url = "https://abbylsmith.github.io/"

    [[params.team.members]]
      name = "Jorge Argueta"
      position = "GPShopper"
      img = "jorge-argueta.jpeg"
      twitter = "jorgeargueta"
      github = "ArgData"

    [[params.team.members]]
      name = "Clara Wang"
      position = "Civis Analytics"
      img = "clara-wang.jpg"
      github = "cwang23"
      url = "https://froodypol.wordpress.com/"

    [[params.team.members]]
      name = "Auden Krauska"
      position = "UW-Madison"
      img = "auden-krauska.jpg"
      twitter = "krauskae"
      github = "krauskae"

    [[params.team.members]]
      name = "Ben Crary"
      position = "LimnoTech"
      img = "ben-crary.jpg"
      twitter = "crary016"
      github = "benjamincrary"

    [[params.team.members]]
      name = "Belinda Chen"
      position = "Centene Corporation"
      img = "belinda-chen.jpg"

    [[params.team.members]]
      name = "Justin Shea"
      position = "Roosevelt University"
      img = "justin-shea.jpg"
      github = "JustinMShea"
      twitter = "justinmshea"

    [[params.team.members]]
      name = "Sydney Purdue"
      position = "Cook County Sheriff's Office"
      img = "sydney-purdue.jpg"
      twitter = "Sydney_NotAUS"
      github = "skpurdue"
      url = "sydneykpurdue.wordpress.com"

    [[params.team.members]]
      name = "Annie Wang"
      position = "R-Ladies Chicago"
      img = "logo.png"
      github = "anniew"

    [[params.team.members]]
      name = "Charlotte Mack"
      position = "R-Ladies Chicago"
      img = "logo.png"
      github = "cymack"
      url = "https://rpubs.com/cymack"
      
# Join us section
  [params.joinus]
  enable = true
  title = "Join us!"
  text = "Applications for the Chicago R Unconference closed at **midnight CST on February 16, 2019**. We hope to see you at next year's unconf!"

# Venue section
  [params.venue]
  enable = true
  title = "Venue"
  text = "The event will be hosted at the [Center for Spatial Data Science](https://spatial.uchicago.edu) at the University of Chicago (5735 S Ellis Ave, Rooms 240 and 236). Please note that the research center is located within Searle Chemical Laboratory. \n\nPaid parking can be found at [Campus North Garage](https://maps.uchicago.edu//location/campus-north-parking-structure-parking/) and [Young Parking Lot](https://maps.uchicago.edu//location/young-parking-lot/), but we encourage you to take public transit to campus in order to save on parking costs."
  map = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2974.751615491931!2d-87.60315248456163!3d41.790566379229254!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880e293e7c052a6d%3A0x760f5c0c7107088f!2sThe+University+of+Chicago+Computation+Institute!5e0!3m2!1sen!2sus!4v1545085956300"


  # Sponsors section

    [params.sponsors_list]
      enable = true
      # Possibility to center items
      #center = true
      title = "Sponsors"
      text = "Thank you to our sponsors for this year's event! If your organization would also like to sponsor the unconference, please email chirunconf [at] gmail com for more information."

      # All the clients' logos are stored under 'static/img/sponsors'.
      # Replace them with your sponsors's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.sponsors]]
        logo = "center-for-spatial-data-science.png"
        link = "https://spatial.uchicago.edu/"
        
      [[params.sponsors]]
        logo = "microsoft-azure.png"
        link = "https://www.r-consortium.org/"
      
      [[params.sponsors]]
        logo = "rstudio-logo.png"
        link = "https://rstudio.com"

  # Contact section
  [params.contact]
    enable = false
    title = "Contact us"
    text  = "Lorem ipsum dolor sit amet consectetur."
    buttonText = "Send message"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "chirunconf@gmail.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0. Thank you to rOpenSci and Nick Tierney for providing a [lovely guide](http://ozunconf18.ropensci.org) for this site."
    text = "[Contact us](mailto:chirunconf@gmail.com) for more information about the event. This page is available at [this repo](https://github.com/chirunconf/chirunconf.github.io). Corrections, changes, and suggestions for improvement are welcome as pull requests."

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
