# Site settings
baseurl = "https://chircollab.github.io"
canonifyurls = true
relativeurls = false
languageCode = "en-us"
title = "Chicago R Collaborative"
location = "Chicago 2020"
theme = "hugo-ropensci-theme"
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Chicago R Collaborative"
  description = "An R community-led, locally-organized hackathon taking place in Chicago, Illinois on March 14-15 2020. Join us at the Chicago R Collab!"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Sorry, but you seem to have become lost."
    text = "Please visit [the front page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Chicago R Collaborative"
    # Optional logo as brand stored in img/
    logo = "logo.png"
    about = "About"
    joinus= "For Participants"
    team = "People"
    venue = "Venue"
    sponsors = "Sponsors"
    contact = "Contact"
    forpartic = "For Participants"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Chicago R Collaborative"
    subtitle = "March 14-15, 2020 • Chicago, Illinois"
    buttonText = "Tell me more"


   # About section
   [params.about]
    enable = true
    title = "About the Chicago R Collaborative"
    text = "Formerly known as the [Chicago R Unconference](http://chirunconf.github.io/), the Chicago R Collaborative is part of an [R Consortium-funded grant](https://www.r-consortium.org/projects/awarded-projects) that supports community-led, locally-organized R development events around the world, otherwise known as R Community Collaboratives. \n\n At the Chicago R Collab, you'll team up with other R users and developers to contribute to open source packages, work on data tools, pursue projects you wish you had time for in your day-to-day work, and learn from others in the R community. Our event is open to a wide range of experience levels and attendee backgrounds (see last year’s [attendee list](https://chirunconf.github.io/#participants)!), and we seek to encourage diverse groups to contribute to the larger R community. \n\n If you’re interested in what you’ll be doing at the event, take a look at [last year’s schedule](https://github.com/chirunconf/chirunconf19/wiki/Schedule), [proposed](https://github.com/chirunconf/chirunconf19/issues) and [completed](https://github.com/chirunconf/chirunconf19/wiki/Unconf-Projects) projects or [Twitter recap](https://twitter.com/search?q=%23chirunconf), peruse our [Code of Conduct](https://chircollab.github.io/coc/), or reach out to chircollab [at] gmail.com if you have questions!"

    # Join us section
      [params.joinus]
      enable = true
      title = "Join us!"
      text = "Applications for the Chicago R Collab closed at **midnight CST on February 2, 2020** We hope to see you at next year's event!"

    # Participants section
      [params.forpartic]
      enable = true
      title = "For Participants"
      text = "If you are participating in this event, make sure to take a look at the event [github repo](https://github.com/chircollab/chircollab20) with issues related to potential project ideas. For information about the event, check out the event [wiki](https://github.com/chircollab/chircollab20/wiki)."



  # Team section
  [params.team]
    enable = true
    # Possibility to center items
    #center = true
    title = "Participants"
    text = "Our team is dedicated to inspiring beginners and those new to open source to contribute to the R community. We've worked in industry and academia alike, and we believe that open source is at its best when it draws from diverse contributors. \n Note: Mentors for this event are denoted with an asterisk."

    # All team member's pictures are stored under 'static/img/team'.
    # Replace them with your own too.
    # Suggestion: Image size should be at least 360px*360px or the alignment might be affected.
    
    [[params.team.members]]
      name = "Angela Li*"
      position = "Center for Spatial Data Science, UChicago"
      img = "angela-li.jpg"
      twitter = "CivicAngela"
      github = "angela-li"
      url = "https://angela-li.github.io"

    [[params.team.members]]
      name = "Emily Riederer*"
      position = "Capital One"
      img = "emily-riederer.jpg"
      twitter = "EmilyRiederer"
      github = "EmilyRiederer"
      url = "https://emilyriederer.netlify.com"

    [[params.team.members]]
      name = "Sydney Purdue*"
      position = "Cook County Sheriff's Office"
      img = "sydney-purdue.jpg"
      twitter = "Sydney_NotAUS"
      github = "skpurdue"
      url = "https://sydneykpurdue.wordpress.com"

    [[params.team.members]]
      name = "William Bonnell*"
      position = "NORC at the University of Chicago"
      img = "william-bonnell.jpg"
      twitter = "_willdebras"
      github = "willdebras"
      url = "https://willdebras.github.io"


    [[params.team.members]]
      name = "Dirk Eddelbuettel*"
      position = "University of Illinois at Urbana-Champaign"
      img = "Dirk Eddelbuettel.jpg"
      twitter = "eddelbuettel"
      github = "eddelbuettel"
      url = "https://willdebras.github.io"
      
      
    [[params.team.members]]
      name = "Zaynaib (Ola) Giwa*"
      img = "Ola Giwa.jpg"
      twitter = "@AmazingSpeciali"
      github = "zaynaib"
      
    [[params.team.members]]
      name = "James Lamb*"
      img = "James Lamb.png"
      twitter = "_jameslamb"
      github = "jameslamb"
      
    [[params.team.members]]
      name = "Eric Nantz*"
      position = "Statistician / Podcaster"
      img = "Eric Nantz.jpg"
      twitter = "theRcast"
      github = "rpodcast"
      
    [[params.team.members]]
      name = "Mauro Lepore*"
      position = "2 degrees investing initiative"
      img = "Mauro Lepore.jpg"
      twitter = "mauro_lepore"
      github = "maurolepore"
      
    [[params.team.members]]
      name = "Sharla Gelfand*"
      img = "Sharla Gelfand.jpg"
      twitter = "sharlagelfand"
      github = "sharlagelfand"
      
    [[params.team.members]]
      name = "Sushmita V Gopalan*"
      position = "Grubhub"
      img = "Sushmita V Gopalan.jpeg"
      twitter = "SushGopalan"
      github = "sushmitavgopalan16"
      
    [[params.team.members]]
      name = "John Blischak*"
      position = "University of Chicago"
      img = "John Blischak.jpg"
      twitter = "jdblischak"
      github = "jdblischak"
      
    [[params.team.members]]
      name = "Mara Averick*"
      position = "RStudio"
      img = "Mara Averick.jpg"
      twitter = "dataandme"
      github = "batpigandme"
      
    [[params.team.members]]
      name = "Jim Gruman"
      position = "CNH Industrial"
      img = "Jim Gruman.jpg"
      twitter = "jim_gruman"
      github = "opus1993"
      
    [[params.team.members]]
      name = "Anh Nhat Tran"
      position = "Northwestern University"
      img = "Anh N Tran.jpg"
      twitter = "anh_n_tran"
      github = "trannhatanh89"
      
    [[params.team.members]]
      name = "Kristi Angel"
      img = "Kristi Angel.jpeg"
      twitter = "kangel09"
      github = "kangel09"
      
    [[params.team.members]]
      name = "Nick Tallant"
      img = "Nicholas Tallant.jpg"
      twitter = "nick__tallant"
      github = "ndtallant"
    
    [[params.team.members]]
      name = "Bryan Berend"
      img = "Bryan Berend.jpg"
      github = "tripleplusone"
      
    [[params.team.members]]
      name = "Kate Doyle"
      position = "University of Chicago"
      img = "Kate Doyle.JPG"
      github = "kdoyle514"
      
    [[params.team.members]]
      name = "Lucy Delaney"
      position = "University of Illinois at Chicago"
      img = "Lucy Delaney.jpg"
      github = "ledelaney"
      
    [[params.team.members]]
      name = "Kanishka Misra"
      position = "Purdue University"
      img = "kanishka-misra.jpg"
      twitter = "iamasharkskin"
      github = "kanishkamisra"
      
    [[params.team.members]]
      name = "Will Dearden"
      position = "Allston Trading"
      img = "Will D.jpeg"
      github = "wdearden"
      
    [[params.team.members]]
      name = "Tomas Okal"
      position = "NORC at the University of Chicago"
      img = "Tom Okal.jpg"
      twitter = "tomasokal"
      github = "tomasokal"
      
    [[params.team.members]]
      name = "Jonathan Keane"
      position = "Socure, Inc"
      img = "Jonathan Keane.png"
      twitter = "jonkeane"
      github = "jonkeane"
      
    [[params.team.members]]
      name = "Edward Visel"
      position = "Uptake"
      img = "Edward Visel.jpeg"
      twitter = "alistaire"
      github = "alistaire47"
      
    [[params.team.members]]
      name = "Stefany Samp"
      img = "Stefany Samp.jpeg"
      twitter = "girasolechi"
      github = "girasolechi"
      
    [[params.team.members]]
      name = "Natalia Block"
      position = "All Stars Project of Chicago"
      img = "Natalia Maciel Block.JPG"
      twitter = "nataliamblock"
      github = "nataliablock"
      
    [[params.team.members]]
      name = "Yifei Hu"
      img = "Patrick.jpg"
      github = "padraighu"
      
    [[params.team.members]]
      name = "Adam Austin"
      position = "Allstate"
      img = "Adam Austin.jpg"
      twitter = "just_add_data"
      github = "ataustin"
      
    [[params.team.members]]
      name = "Adarsh Mathew"
      position = "University of Chicago"
      img = "Adarsh Mathew.jpg"
      twitter = "adarshmathew92"
      github = "adarshmathew"
      
    [[params.team.members]]
      name = "Haoen Cui"
      img = "Haoen Cui.png"
      github = "Haoen-Cui"
      
    [[params.team.members]]
      name = "Anna Vasylytsya"
      img = "Anna Vasylytsya.jpg"
      github = "annnvv"
      
    [[params.team.members]]
      name = "Sandy Morales"
      img = "Sandy Morales.jpg"

      
    [[params.team.members]]
      name = "Moksha Menghaney"
      position = "Centre for Spatial Data Science at University of Chicago"
      img = "Moksha Menghaney.png"
      twitter = "MokshaMenghaney"
      
    [[params.team.members]]
      name = "Benjamin Ortiz"
      img = "Benjamin Ortiz Ulloa.jpg"
      twitter = "plzbeemyfriend"
      github = "beemyfriend"
      
      



# Venue section
  [params.venue]
  enable = true
  title = "Venue"
  text = "The event will be hosted at the [Center for Spatial Data Science](https://spatial.uchicago.edu) at the University of Chicago (5735 S Ellis Ave, Rooms 240 and 236). Please note that the research center is located within Searle Chemical Laboratory. \n\nPaid parking can be found at [Campus North Garage](https://maps.uchicago.edu//location/campus-north-parking-structure-parking/) and [Young Parking Lot](https://maps.uchicago.edu//location/young-parking-lot/), but we encourage you to take public transit to campus in order to save on parking costs."
  map = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2974.751615491931!2d-87.60315248456163!3d41.790566379229254!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x880e293e7c052a6d%3A0x760f5c0c7107088f!2sThe+University+of+Chicago+Computation+Institute!5e0!3m2!1sen!2sus!4v1545085956300"


  # Sponsors section

    [params.sponsors_list]
      enable = false
      # Possibility to center items
      #center = true
      title = "Sponsors"
      text = "Thank you to our sponsors for this year's event! If your organization would also like to sponsor the Chicago R Collab, please email chircollab [at] gmail com for more information."

      # All the clients' logos are stored under 'static/img/sponsors'.
      # Replace them with your sponsors's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.sponsors]]
        logo = "center-for-spatial-data-science.png"
        link = "https://spatial.uchicago.edu/"
        
      [[params.sponsors]]
        logo = "microsoft-azure.png"
        link = "https://www.r-consortium.org/"
      
      [[params.sponsors]]
        logo = "rstudio-logo.png"
        link = "https://rstudio.com"

  # Contact section
  [params.contact]
    enable = false
    title = "Contact us"
    text  = "Lorem ipsum dolor sit amet consectetur."
    buttonText = "Send message"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

    email = "chircollab@gmail.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

    # 'warning' defines error messages for invalid inputs
    [params.contact.form.name]
      text = "Your Name *"
      warning = "Please enter your name."

    [params.contact.form.email]
      text = "Your Email *"
      warning = "Please enter your email address."

    [params.contact.form.phone]
      text = "Your Phone *"
      warning = "Please enter your phone number."

    [params.contact.form.message]
      text = "Your Message *"
      warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Published under the Apache License 2.0. Thank you to rOpenSci and Nick Tierney for providing a [lovely guide](http://ozunconf18.ropensci.org) for this site."
    text = "You can [contact us](mailto:chircollab@gmail.com) by email for more information about the event. Because we want to make sure everyone who attends this event has a safe and comfortable experience, this event follows a [code of conduct](https://chircollab.github.io/coc/). \n\n The source code for this page is available at [this Github repository](https://github.com/chircollab/chircollab.github.io). Corrections, changes, and suggestions for improvement are welcome as pull requests."

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
